### PR TITLE
Support GraphQL 0.12 invalid literals

### PR DESCRIPTION
**Pull request by jbblanchet**
- Support returning undefined for invalid literals, like detailed in graphql/graphql-js#1104
- Support Kind.NULL, with required upgrade of minimum version to 0.8
- Upgraded dev dependencies
- Async unit tests return promise for better error reporting
- Added linting rule to support chai `to.be.undefined`

### CODE REVIEW

**Comment by taion** [comment]
Thanks! I'm going to make a few small tweaks in a sec

**Comment by jbblanchet** [comment]
@taion If it's quicker for you to point out here what need to be changed, I don't mind doing the changes.

**Comment by taion** [comment]
Updated, can you take a quick look?

**Comment by jbblanchet** [comment]
Looks good to me. Didn't want to refactor too much stuff so I went for the minimum :smile: 

Only thing that seems to be missing for a release if the version number.

**Comment by taion** [comment]
We do version bumps separately. Will get back.

**Comment by taion** [comment]
v0.2.0 released

**Comment by jbblanchet** [comment]
Thanks for the quick release!

**Pull request merged**
